### ISSUE TITLE
Write proper README

### ISSUE THREAD

**Issue by tillkruss** [cachewerk/bref-laravel-bridge#34]
- Setup
- Queues
- FS
- Octane

**Comment by kris914g** [comment]
It would be nice to include some more about how to setup Octane properly.

**Comment by kris914g** [comment]
Do we have an example somewhere about how to setup Octane, right now I have tried with Swoole and default config, but I'm not sure if it is setup and registered with the bride at all. I also included the octane runtime in the serverless config.

**Comment by tillkruss** [comment]
@kris914g All you need is:

```yaml
functions:
  web:
    handler: php/runtime.php
    timeout: 20
    reservedConcurrency: ${param:reservedConcurrency}
    provisionedConcurrency: ${param:provisionedConcurrency}
    environment:
      APP_RUNTIME: octane
      BREF_LOOP_MAX: 250
      BREF_BINARY_RESPONSES: 1
    layers:
      - ${bref:layer.php-81}
    events:
      - httpApi: '*'
```
